# Generated by Django 5.1.1 on 2024-09-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='ContactFormDetails',
        ),
        migrations.AlterModelTable(
            name='contactformdetails',
            table='ContactFormDetails',
        ),
    ]
