# Generated by Django 5.1.1 on 2024-09-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_rename_contact_contactformdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformdetails',
            name='created_at',
        ),
    ]
