# Generated by Django 5.1.1 on 2024-09-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_remove_contactformdetails_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformdetails',
            name='subject',
            field=models.CharField(max_length=500),
        ),
    ]
